[project]
name = "azathoth"
revision = "1.0"

[profiles.default]
GEMINI_API_KEY = { description = "GEMINI_API_KEY secret", required = true, providers = ["shared"] }
PYPI_TOKEN = { description = "PYPI_TOKEN secret", required = true }

[profiles.development]
