import asyncio
from datetime import datetime
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

from azathoth.config import config
from azathoth.core.ingest import ingest, detect_type, IngestType, get_subpath_context
from azathoth.core.utils import format_size

console = Console()

def main(
    path: str = typer.Argument(".", help="Path to scan"),
    save: bool = typer.Option(True, "--save/--no-save", help="Save report"),
    output: Optional[Path] = typer.Option(None, "--output", "-o", help="Custom output path"),
):
    """
    Structural ingestion. Like `az ingest` but discards file content.
    Saves the structure report silently.
    """
    async def _run():
        ctx = await get_subpath_context(path)
        if ctx:
            root_name, rel_path = ctx
            console.print(f"[dim]Context:[/dim] Detected Git Root at [bold]{root_name}[/]")
            console.print(f"[dim]Scope:[/dim]   Restricting scan to [bold]{rel_path}[/]")

        with console.status(f"⠋ Scanning [cyan]{path}[/cyan]...", spinner="dots"):
            try:
                result = await ingest(path)
            except Exception as e:
                console.print(f"[bold red]✗ Scan failed:[/] {e}")
                raise typer.Exit(1)

        # Build clean report
        report_text = (
            f"STRUCTURE REPORT: {result.suggested_filename}\n"
            f"{'='*60}\n"
            f"{result.summary}\n\n"
            f"TREE\n"
            f"{'='*60}\n"
            f"{result.tree}\n\n"
            f"Generated by Azathoth `az ls`"
        )

        # Summary panel
        table = Table(box=None, show_header=False, padding=(0, 1))
        table.add_column(style="dim")
        table.add_column(style="bold cyan")
        table.add_row("Files", str(result.metrics.file_count))
        
        from azathoth.core.utils import estimate_tokens
        table.add_row("Tokens (metadata)", f"{estimate_tokens(result.tree):,}")
        
        if save or output:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            # REACIVE FILENAME: uses result.suggested_filename just like ingest
            filename = f"{result.suggested_filename}-{timestamp}.txt"
            save_path = output or (config.reports_dir / filename)
            
            save_path.write_text(report_text, encoding="utf-8")
            table.add_row("Saved to", f"@{save_path}")

        console.print(Panel(
            table,
            title="[bold green]✓ Directory Scanned![/]",
            expand=False,
            border_style="green",
        ))

    asyncio.run(_run())
